### ISSUE TITLE
扫描时候没携带参数

### ISSUE THREAD

**Issue by loveshell** [0xbug/SQLiScanner#1]
使用的是charles 4.0，记录的har文件里有参数的，上传进行后
如下图
![48f7394d-3413-4996-a7b3-07a529a0b4c8](https://cloud.githubusercontent.com/assets/1836888/18626677/0e31e108-7e89-11e6-83e3-bc40b1baa1ad.png)

传递过来的数据没有参数

测试地址如下：
http://testphp.vulnweb.com/listproducts.php?cat=1

**Comment by 0xbug** [comment]
@loveshell  请重新上传一下图片

**Comment by 0xbug** [comment]
@loveshell 你应该是在 URL 里加了  单引号导致 sqlmap 不能正确运行；前端默认显示的是路径不包含请求参数
