### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the NAME value.

### ISSUE THREAD

**Issue by Duanexiao** [0xbug/SQLiScanner#15]
你好，我按照你的readme文档操作的，django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the NAME value.出现这个报错信息

**Comment by 0xbug** [comment]
@Duanexiao 请提供一下Python版本、数据库配置（打上马赛克）

**Comment by Duanexiao** [comment]
@0xbug 谢谢，问题已解决。说明文档不够详细，希望有空能把说明文档弄详细点，谢谢！
