### ISSUE TITLE
这个的应用场景是怎样的？怎么会要把请求通过代理抓下来再上传上去这么别扭的？面向web扫描的，应该有url就行吧。

### ISSUE THREAD

**Issue by tuhaolam** [0xbug/SQLiScanner#4]

**Comment by 0xbug** [comment]
@tuhaolam 部署到一台机器后，其他人也可以上传文件进行扫描，操作简便；有些URL需要登录才能扫描，har格式更适合保存请求。

**Comment by vTNT** [comment]
弱弱的问一下  上传的文件具体格式是什么？ web log?

**Comment by 0xbug** [comment]
@vTNT [har 格式](http://it.taocms.org/04/3218.htm)，可以使用 Charles 的导出功能，保存格式选择.har
![image](https://cloud.githubusercontent.com/assets/12611275/18945635/097cffa8-865e-11e6-9688-a0dcd59b6772.png)
![image](https://cloud.githubusercontent.com/assets/12611275/18945657/21a3efba-865e-11e6-926a-f819b321c4d2.png)
